name: Potts
channels:
  - defaults
dependencies:
  - blas=1.0
  - blosc=1.21.3
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.12.0
  - ca-certificates=2025.2.25
  - contourpy=1.3.1
  - cycler=0.11.0
  - expat=2.7.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - h5py=3.12.1
  - hdf5=1.12.1
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libcurl=8.12.1
  - libcxx=17.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.16
  - packaging=24.2
  - pillow=11.1.0
  - pip=25.1
  - py-cpuinfo=9.0.0
  - pyparsing=3.2.0
  - python=3.12.11
  - python-dateutil=2.9.0post0
  - readline=8.2
  - scipy=1.15.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - tables=3.9.2
  - tk=8.6.14
  - tornado=6.5.1
  - tzdata=2025b
  - unicodedata2=15.1.0
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - primme==3.2.3
prefix: /Users/claudia/miniconda3/envs/Potts
